name: 'ecom_warehouse'
version: '1.0.0'
config-version: 2

profile: 'bigquery_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  ecom_warehouse:
    staging:
      +materialized: view
    marts:
      +materialized: table
